version: 2

project_name: piece-server

release:
  github:
    owner: lexluthr
    name: piece-server

builds:
  - id: piece-server
    main: ./main.go
    binary: piece-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - id: tarball
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

nfpms:
  - formats:
      - deb
      - rpm
    vendor: "LexLuthr"
    maintainer: "LexLuthr <lexluthr@curiostorage.org>"
    description: "Piece Server"
    homepage: "https://github.com/lexluthr/piece-server"
    license: "MIT"
